# Generated by Django 4.2.13 on 2024-07-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('check_in_date_and_time', models.DateTimeField()),
                ('check_out_date_and_time', models.DateTimeField()),
                ('destination', models.CharField(choices=[('Janjehli Resort', 'Janjehli Resort'), ('Kandaghat Shimla Resort', 'Kandaghat Shimla Resort'), ('Kanatal Resort', 'Kanatal Resort'), ('Mussoorie Resort', 'Mussoorie Resort'), ('Danish Villa Resort', 'Danish Villa Resort'), ('Le Poshe Resort', 'Le Poshe Resort'), ('Mount Serene Resort', 'Mount Serene Resort')], max_length=30)),
                ('no_of_persons', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('have_you_availed_membership', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('type_of_room', models.CharField(choices=[('S', 'Studio Apartment'), ('1', '1-Bedroom Apartment'), ('2', '2-Bedroom Apartment')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Roomsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('studio', models.IntegerField()),
                ('onebed', models.IntegerField()),
                ('twobed', models.IntegerField()),
            ],
        ),
    ]
