# Generated by Django 4.2.13 on 2024-07-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristapp2', '0002_bookingmodel_roomsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbackmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.TextField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='destination',
            field=models.CharField(choices=[('Janjehli Resort', 'Janjehli Resort'), ('Kandaghat Shimla Resort', 'Kandaghat Shimla Resort'), ('Kanatal Resort', 'Kanatal Resort'), ('Mussoorie Resort', 'Mussoorie Resort')], max_length=30),
        ),
    ]
