# Generated by Django 5.2.3 on 2025-06-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristapp2', '0004_resort'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
