# Generated by Django 5.2.3 on 2025-06-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristapp2', '0005_resort_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/800x400.png?text=No+Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resort',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resort',
            name='resort_type',
            field=models.CharField(max_length=50),
        ),
    ]
